# -*- coding: utf-8 -*-
"""AI EXP 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7CKQsuNSCFsSlcppBBApHXivcTQpQgN
"""

from collections import deque
def bfs(start, goal):
    q = deque([(start, [])])
    visited = set()
    while q:
        state, path = q.popleft()
        if state in visited:
            continue
        visited.add(state)
        path = path + [state]
        if state == goal:
            for s in path:
                print(s)
            return
        i = state.index(0)
        moves = []
        if i not in [0,1,2]: moves.append(i-3)
        if i not in [6,7,8]: moves.append(i+3)
        if i not in [0,3,6]: moves.append(i-1)
        if i not in [2,5,8]: moves.append(i+1)
        for m in moves:
            lst = list(state)
            lst[i], lst[m] = lst[m], lst[i]
            q.append((tuple(lst), path))
start = tuple(map(int, input().split()))
goal = tuple(map(int, input().split()))
bfs(start, goal)