# -*- coding: utf-8 -*-
"""AI EXP 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7CKQsuNSCFsSlcppBBApHXivcTQpQgN
"""

from collections import deque

def water_jug_bfs(jug1, jug2, target):
    visited = set()
    queue = deque()

    # Initial state
    queue.append((0, 0, []))

    while queue:
        x, y, path = queue.popleft()

        # If already visited, skip
        if (x, y) in visited:
            continue

        visited.add((x, y))
        path = path + [(x, y)]

        # Check goal
        if x == target or y == target:
            return path

        # Generate all possible states
        next_states = [
            (jug1, y),  # Fill Jug1
            (x, jug2),  # Fill Jug2
            (0, y),     # Empty Jug1
            (x, 0),     # Empty Jug2
            # Pour Jug1 -> Jug2
            (x - min(x, jug2 - y), y + min(x, jug2 - y)),
            # Pour Jug2 -> Jug1
            (x + min(y, jug1 - x), y - min(y, jug1 - x))
        ]

        for state in next_states:
            if state not in visited:
                queue.append((state[0], state[1], path))

    return None


# Example
jug1 = 4
jug2 = 3
target = 2

solution = water_jug_bfs(jug1, jug2, target)

if solution:
    print("Steps to reach the solution:")
    for step in solution:
        print(step)
else:
    print("No solution found")