# -*- coding: utf-8 -*-
"""AI EXP 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7CKQsuNSCFsSlcppBBApHXivcTQpQgN
"""

import itertools

def solve_cryptarithm():
    letters = ('S','E','N','D','M','O','R','Y')
    digits = range(10)

    for perm in itertools.permutations(digits, len(letters)):
        s, e, n, d, m, o, r, y = perm

        # Leading digit should not be zero
        if s == 0 or m == 0:
            continue

        send  = 1000*s + 100*e + 10*n + d
        more  = 1000*m + 100*o + 10*r + e
        money = 10000*m + 1000*o + 100*n + 10*e + y

        if send + more == money:
            print("Solution Found:")
            print(f"S={s}, E={e}, N={n}, D={d}, M={m}, O={o}, R={r}, Y={y}")
            print(f"{send} + {more} = {money}")
            return

solve_cryptarithm()