# -*- coding: utf-8 -*-
"""EXP 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7CKQsuNSCFsSlcppBBApHXivcTQpQgN
"""

def vacuum_cleaner(location, status_A, status_B):
    steps = []

    while status_A == "Dirty" or status_B == "Dirty":

        if location == "A":
            if status_A == "Dirty":
                steps.append("Suck at A")
                status_A = "Clean"
            else:
                steps.append("Move Right")
                location = "B"

        elif location == "B":
            if status_B == "Dirty":
                steps.append("Suck at B")
                status_B = "Clean"
            else:
                steps.append("Move Left")
                location = "A"

    return steps


# Example Input
location = "A"
status_A = "Dirty"
status_B = "Dirty"

result = vacuum_cleaner(location, status_A, status_B)

print("Steps:")
for step in result:
    print(step)