# -*- coding: utf-8 -*-
"""EXP 10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7CKQsuNSCFsSlcppBBApHXivcTQpQgN
"""

graph = {
    'A': ['B','C'],
    'B': ['A','C','D'],
    'C': ['A','B','D'],
    'D': ['B','C']
}

colors = ['Red','Green','Blue']
result = {}

def is_safe(node, color):
    for neighbour in graph[node]:
        if neighbour in result and result[neighbour] == color:
            return False
    return True

def solve(nodes, index):
    if index == len(nodes):
        return True

    node = nodes[index]

    for color in colors:
        if is_safe(node, color):
            result[node] = color
            if solve(nodes, index + 1):
                return True
            del result[node]

    return False

nodes = list(graph.keys())

if solve(nodes, 0):
    print(result)
else:
    print("No solution found")