# -*- coding: utf-8 -*-
"""EXP 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7CKQsuNSCFsSlcppBBApHXivcTQpQgN
"""

import itertools

def calculate_distance(path, graph):
    distance = 0
    for i in range(len(path) - 1):
        distance += graph[path[i]][path[i+1]]
    distance += graph[path[-1]][path[0]]  # Return to start
    return distance

def tsp(graph):
    cities = list(graph.keys())
    min_path = None
    min_cost = float('inf')

    for perm in itertools.permutations(cities):
        cost = calculate_distance(perm, graph)

        if cost < min_cost:
            min_cost = cost
            min_path = perm

    return min_path, min_cost


# Example Graph (Distance Matrix)
graph = {
    'A': {'A':0, 'B':10, 'C':15, 'D':20},
    'B': {'A':10, 'B':0, 'C':35, 'D':25},
    'C': {'A':15, 'B':35, 'C':0, 'D':30},
    'D': {'A':20, 'B':25, 'C':30, 'D':0}
}

path, cost = tsp(graph)

print("Shortest Path:", path)
print("Minimum Cost:", cost)