# -*- coding: utf-8 -*-
"""EXP 9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7CKQsuNSCFsSlcppBBApHXivcTQpQgN
"""

import heapq

graph = {
    'A': [('B',1), ('C',3)],
    'B': [('D',3), ('E',1)],
    'C': [('F',5)],
    'D': [],
    'E': [('F',2)],
    'F': []
}

heuristic = {
    'A':6,
    'B':4,
    'C':4,
    'D':2,
    'E':1,
    'F':0
}

def astar(start, goal):
    pq = [(heuristic[start], 0, start, [])]
    visited = set()

    while pq:
        f, cost, node, path = heapq.heappop(pq)

        if node in visited:
            continue

        path = path + [node]

        if node == goal:
            return path, cost

        visited.add(node)

        for neigh, weight in graph[node]:
            heapq.heappush(
                pq,
                (cost + weight + heuristic[neigh],
                 cost + weight,
                 neigh,
                 path)
            )

path, cost = astar('A', 'F')
print("Path:", path)
print("Cost:", cost)